DECLARE @SITE INT
DECLARE @OLD_STUDENT_ID INT

@SITE = 0
@OLD_STUDENT_ID = 0

DECLARE @NEW_LAST_ID INT = (SELECT ID FROM LOC WHERE CD = @SITE) + 1
UPDATE LOC SET ID = @NEW_LAST_ID WHERE CD = @SITE
UPDATE IDN SET ID = @NEW_LAST_ID WHERE ID = @OLD_STUDENT_ID
UPDATE PWA SET PID = @NEW_LAST_ID WHERE PID = @OLD_STUDENT_ID
UPDATE PWS SET ID = @NEW_LAST_ID WHERE ID = @OLD_STUDENT_ID
UPDATE TECH SET BID = @NEW_LAST_ID WHERE BID = @OLD_STUDENT_ID