FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y gcc libxml2-dev libxslt-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Copy everything in the current local folder to /app in the container
COPY . . 
EXPOSE 5000
CMD ["python", "app.py"]